### ISSUE TITLE
Pass error as a parameter to the children function

### ISSUE THREAD

**Issue by dimas-cyriaco** [jomaxx/react-async-await#1]
I just started working in something pretty much like this, and i would love to just use this package instead of implement the whole thing.

But I would like to use more than one 'Async' on the same component, so i would need to have separate error handler for each instance.

Are you willing to accept a PR with this change?

**Comment by jomaxx** [comment]
hey @dimascyriaco i'm open to PRs but it sounds like your use case can be solved by using `Promise.all` or handling the error state. This component is meant to throw uncaught errors so it bubbles up to an Error boundary. Does the following examples work:

```jsx
<Async await={Promise.all([promiseA, promiseB])}>
  {([a, b]) => ...}
</Async>
```

```jsx
<Async await={promise.catch(error => ({ error }))}>
  {result =>(
    <div>
      {result === undefined && 'Loading'}
      {result && result.error && 'Error'}
      {result && 'Loaded'}
    </div>
  )}
</Async>
```

In the future, I intend to add support for the Suspense feature https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html

**Comment by dimas-cyriaco** [comment]
Sorry, I think I wasn't clear. What I meant was something like this:

``` js
const MyComponent = (props) => (
  <Async await={promiseA}>
    {({ error }) => /* handle this failure one way */ }
  </Async>

  { /* more stuff */ }

  <Async await={promiseB}>
    {({ error }) => /* handle this failure other way */ }
  </Async>
)
```

What do you think?

**Comment by jomaxx** [comment]
This is currently possible as long as you handle the error. uncaught errors will throw in the react tree and should be caught by an error boundary. 

```jsx
const promiseA = getUser(1).then(
  value => ({ value }),
  error => ({ error })
);

const promiseB = getUser(2).then(
  value => ({ value }),
  error => ({ error })
);

const MyComponent = (props) => (
  <Async await={promiseA}>
    {({ error }) => /* handle this failure one way */ }
  </Async>

  { /* more stuff */ }

  <Async await={promiseB}>
    {({ error }) => /* handle this failure other way */ }
  </Async>
)

```

Another thing you could do is create a `Catch` component that uses Error Boundaries.

```jsx
class Catch extends React.Component {
  state = {};  

  componentDidCatch(error) {
    this.setState({ error });
  }

  render() {
    return this.props.children(this.state.error);
  }
}

const MyComponent = (props) => (
  <Catch>
    {error => (
      <Async await={promiseA}>
        {...}
      </Async>
    )}
  </Catch>

  { /* more stuff */ }

  <Catch>
    {error => (
      <Async await={promiseB}>
        {...}
      </Async>
    )}
  </Catch>
)

```

**Comment by dimas-cyriaco** [comment]
I think that should do the trick. Seems a bit verbose, but I'll give it a try.

**Comment by dimas-cyriaco** [comment]
Just had an idea. What about something like this:

``` js
<Async
  await={promiseA}
  catch={(error) => {...}}
>
  {...}
</Async>
```
If you don't pass the catch function it would keep the current behaviour. It would be backward compatible and would avoid having to write the boilerplate `then` on the promises.

And it follows the `await promise.catch()` mental model that people already have.

**Comment by jomaxx** [comment]
I like the catch prop idea! could be useful for debugging/logging and i guess you can always rethrow the error as well. 

would catch work like this:

```jsx
<Async
  await={promiseA}
  catch={error => ({ error })}
>
  {({ error }) => ...}
</Async>
```

**Comment by jomaxx** [comment]
~~if we add `catch` i think there is value in adding `then`.~~

~~these could just be props for mapping the resolved/rejected values to the value passed to the render callback. although u can already map the value for then so maybe not~~

You can already map in the render callback so no need to add `then` support.

**Comment by jomaxx** [comment]
@dimascyriaco let me know if you want to do a PR otherwise i'm happy to tackle it

**Comment by dimas-cyriaco** [comment]
I'll do a PR. :+1:
